const contacts = [
  { name: "Alice", lastMsg: "Hi there!" },
  { name: "Bob", lastMsg: "Hello" },
  { name: "Charlie", lastMsg: "" },
  { name: "David", lastMsg: "Goodbye" },
  { name: "Eve", lastMsg: "" },
  { name: "Frank", lastMsg: "How are you?" },
  { name: "Grace", lastMsg: "See you later" },
  { name: "Hank", lastMsg: "Nice meeting you" },
  { name: "Ivy", lastMsg: "" },
  { name: "Jack", lastMsg: "Take care" },
  { name: "Kelly", lastMsg: "Good morning" },
  { name: "Liam", lastMsg: "" },
  { name: "Mia", lastMsg: "" },
  { name: "Noah", lastMsg: "Have a great day" },
  { name: "Olivia", lastMsg: "" },
  { name: "Penny", lastMsg: "How's it going?" },
  { name: "Quinn", lastMsg: "" },
  { name: "Ryan", lastMsg: "See you soon" },
  { name: "Sophia", lastMsg: "" },
  { name: "Tom", lastMsg: "" },
  { name: "Zoe", lastMsg: "Nice talking to you" },
];

const initialMsgs = [
  { type: "incoming", message: "Hello there!" },
  { type: "outgoing", message: "Hi!" },
  { type: "incoming", message: "How are you today?" },
  { type: "outgoing", message: "I'm good, thanks!" },
  { type: "incoming", message: "What have you been up to?" },
  { type: "outgoing", message: "Not much, just working." },
  { type: "incoming", message: "That sounds busy!" },
  {
    type: "incoming",
    message: "By the way, did you watch the game last night?",
  },
  { type: "outgoing", message: "Yes, it was amazing!" },
  { type: "outgoing", message: "I can't believe they won!" },
  { type: "incoming", message: "I know, right? It was a nail-biter!" },
  { type: "incoming", message: "I'm so glad we decided to watch it together." },
  { type: "outgoing", message: "Me too! We should do it again sometime." },
  { type: "outgoing", message: "Definitely!" },
  { type: "incoming", message: "Okay, see you later!" },
  { type: "incoming", message: "Take care!" },
  { type: "outgoing", message: "You too!" },
  { type: "outgoing", message: "Goodbye!" },
  { type: "incoming", message: "Hey, how's it going?" },
  { type: "outgoing", message: "Not too bad, thanks." },
  { type: "incoming", message: "What's new in your life?" },
  { type: "outgoing", message: "I started a new project at work." },
  { type: "incoming", message: "That sounds interesting." },
  { type: "outgoing", message: "Yes, it's challenging but exciting." },
  { type: "incoming", message: "I'm sure you'll do great!" },
  { type: "outgoing", message: "Thanks for the support!" },
  { type: "incoming", message: "Anytime!" },
  { type: "incoming", message: "Gotta go now. Catch you later." },
  { type: "outgoing", message: "Sure, talk to you later." },
];

export { contacts, initialMsgs };
